version: '2'
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db/
  heyburrito:
    image: chralp/heyburrito:latest
    ports:
      - "3333:3333"
      - "8080:8080"
    environment:
      - BOT_NAME=heyegg
      - DATABASE_DRIVER=mongodb
      - MONGODB_URL=mongodb+srv://tom:future2023@fdi-cluster.y9juexk.mongodb.net
      - MONGODB_DATABASE=hey-egg
      - SLACK_API_TOKEN=xoxb-2513029522-5222937352609-qt1weLnBz3VjzImIhWERvvrO
      - "SLACK_EMOJI_INC=:goldenegg:"
      - "SLACK_EMOJI_DEC=:rottenburrito:"
      - SLACK_DAILY_CAP=5
      - ENABLE_DECREMENT=false
    links:
      - mongodb
